### ISSUE TITLE
docker exits just after starting

### ISSUE THREAD

**Issue by Gituseron** [imfing/keras-flask-deploy-webapp#62]
Thank you for your quick responses and all the edits done today! I have tried new docker right now, but the problem is it quits just after the start. I tried building docker both with model in folder Models (exactly I used h5 model from teachable machine by google) and without it, but nevertheless - simply exits. As for local install:

```
Traceback (most recent call last):
  File &quot;app.py&quot;, line 5, in &lt;module&gt;
    from flask import Flask, redirect, url_for, request, render_template, Response, jsonify, redirect
ImportError: No module named flask
```

Even though it is installed within requirements.txt

**Comment by imfing** [comment]
did you install and run using `docker`?

**Comment by Gituseron** [comment]
yes, certainly

**Comment by imfing** [comment]
after the container image is successfully built, can you try run with:

```bash
docker run -it --rm -p 5000:5000 --entrypoint /bin/bash keras_flask_app
```
which should give you a shell, and from there, try to run `python3 main.py` and see what error it complains

**Comment by Gituseron** [comment]
Thank you. I've tried. it says: Illegal instruction (core dumped)

**Comment by brsolomon-deloitte** [comment]
Confirmed this is broken as shown in the readme. It would be nice to have an updated version that works as shown.

```
$ docker run -it --rm -p 5000:5000 keras_flask_app
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2023-05-09 00:51:43.870983: F tensorflow/core/lib/monitoring/sampler.cc:42] Check failed: bucket_limits_[i] > bucket_limits_[i - 1] (0 vs. 10)
qemu: uncaught target signal 6 (Aborted) - core dumped
```

Using: MacOS 13.3.1, Docker version 20.10.23, build 7155243.

**Comment by imfing** [comment]
@Gituseron  @brsolomon-deloitte  Thank you for the feedback, I can reproduce this issue and I think the main reason might be the Docker image being too old and packages outdated.
I will update the Dockerfile to resolve it, and provide prebuilt images.

**Comment by brsolomon-deloitte** [comment]
In my case, it was actually because Tensorflow does not distribute Docker images (nor is underlying tensorflow supported on) MacOS M1 ARM chips. It may very well be that there is no issue with this app on amd64.

**Comment by imfing** [comment]
yeah, since the docker base image was fairly old which is amd64 only, and plus the tensorflow package is outdated without prebuilt wheel for Arm architecture. I've fixed the Dockerfile in #64 which should address this issue.

**Comment by imfing** [comment]
@Gituseron @brsolomon-deloitte I've built and published prebuilt images (for both amd64 and arm64) to GitHub container registry, see [Package keras-flask-deploy-webapp](https://github.com/imfing/keras-flask-deploy-webapp/pkgs/container/keras-flask-deploy-webapp)
Now instead of building images on your own, you can:

```bash
$ docker run --rm -p 5000:5000 ghcr.io/imfing/keras-flask-deploy-webapp:v0.1.1
```

which should work out-of-box on M1 macbook

**Comment by brsolomon-deloitte** [comment]
@imfing awesome, thank you!
